# Packet-row foreground/background colors for the Wireshark-style capture
# table, ported from Wireshark's own default coloring rules
# (https://github.com/RayHightower/wireshark/blob/master/colorfilters —
# 16-bit-per-channel [fg][bg] values converted to 8-bit hex). That rule set
# happens to already assume a near-black #12272E backdrop for every
# protocol-family row, which is why it drops directly onto this app's
# existing dark packet-capture theme without needing to invert anything.
#
# Only the rules that can actually occur in traffic generated by this
# platform (a ping/iperf-style traffic_test, or the P4CHECKERS UDP
# protocol) are implemented — Wireshark's own defaults also include rules
# for HTTP, SMB, DCERPC, HSRP/OSPF/BGP/STP, SCTP, IPX, etc. that this
# app's exercises never produce, so porting them would be dead code.
module PacketColoring
  include PacketChecksum

  WS_DARK = '#12272e'

  WS_COLORS = {
    icmp_errors: { fg: WS_DARK,   bg: '#b7f774' }, # destination unreachable / TTL exceeded / redirect
    arp:         { fg: '#faf0d7', bg: WS_DARK    },
    tcp_rst:     { fg: '#a40000', bg: '#fffc9c'  },
    ttl_low:     { fg: '#a40000', bg: '#ecf0eb'  },
    checksum_bad:{ fg: WS_DARK,   bg: '#f78787'  }, # same salmon family as Wireshark's "Bad TCP"
    tcp_syn_fin: { fg: '#a0a0a0', bg: WS_DARK    },
    icmp:        { fg: '#fce0ff', bg: WS_DARK    },
    tcp:         { fg: '#e7e5ff', bg: WS_DARK    },
    udp:         { fg: '#daeeff', bg: WS_DARK    },
    broadcast:   { fg: '#ffffff', bg: '#babdb6'  },
  }.freeze

  # Destination-unreachable / source-quench / redirect / time-exceeded —
  # the exact type values Wireshark's own "ICMP errors" rule matches.
  # ICMPv4 and ICMPv6 use different numbering for these, hence two sets.
  ICMPV4_ERROR_TYPES = [3, 4, 5, 11].freeze
  ICMPV6_ERROR_TYPES = [1, 2, 3, 4].freeze

  TCP_RST     = 0x04
  TCP_SYN_FIN = 0x01 | 0x02

  # `proto` is TcpdumpParser's text-classified protocol — kept only as a
  # fallback for submissions/hosts predating structured captures, since its
  # regex doesn't handle tcpdump's `ip.port` suffix (e.g.
  # "10.0.1.2.5000 > 10.0.2.2.6000: UDP") and so under-detects TCP/UDP in
  # particular. `structured_pkt` is the matching header-decoded dict from
  # Submission#parsed_structured_packet_captures (see PacketDetailFormatter)
  # — when present, layer-key presence is used instead, which is always
  # correct regardless of that text-parsing gap. Returns a { fg:, bg: }
  # hex-color hash, or nil to fall back to the table's default (unstyled)
  # row.
  #
  # Mirrors Wireshark's own first-match-wins rule priority.
  def packet_row_colors(proto, structured_pkt)
    icmp = structured_pkt && structured_pkt['icmp']
    tcp  = structured_pkt && structured_pkt['tcp']
    udp  = structured_pkt && structured_pkt['udp']
    ttl  = structured_pkt && (structured_pkt.dig('ipv4', 'ttl') || structured_pkt.dig('ipv6', 'hop_limit'))

    return WS_COLORS[:icmp_errors]  if icmp_error?(structured_pkt, icmp)
    return WS_COLORS[:arp]          if proto == 'ARP'
    return WS_COLORS[:tcp_rst]      if tcp && tcp['flags'].to_i.anybits?(TCP_RST)
    return WS_COLORS[:ttl_low]      if ttl && ttl < 5
    return WS_COLORS[:checksum_bad] if structured_pkt && checksum_bad?(structured_pkt)
    return WS_COLORS[:tcp_syn_fin]  if tcp && tcp['flags'].to_i.anybits?(TCP_SYN_FIN)
    return WS_COLORS[:icmp]         if icmp || proto == 'ICMP'
    return WS_COLORS[:tcp]          if tcp || proto == 'TCP'
    return WS_COLORS[:udp]          if udp || proto == 'UDP'
    return WS_COLORS[:broadcast]    if broadcast_mac?(structured_pkt&.dig('ethernet', 'dst_mac'))

    nil
  end

  private

  def icmp_error?(structured_pkt, icmp)
    return false unless icmp
    types = structured_pkt['ipv6'] ? ICMPV6_ERROR_TYPES : ICMPV4_ERROR_TYPES
    types.include?(icmp['type'])
  end

  def checksum_bad?(pkt)
    %w[ipv4 icmp tcp udp].any? { |layer| pkt[layer] && !valid_checksum?(pkt, layer) }
  end

  # Wireshark's own rule is the raw filter `eth[0] & 1` — the
  # least-significant bit of the destination MAC's first octet, set for
  # both broadcast (ff:ff:ff:ff:ff:ff) and multicast destinations.
  def broadcast_mac?(mac)
    return false if mac.blank?
    mac.split(':').first.to_i(16).odd?
  end
end
